### PR TITLE
Undo redo

### PR DESCRIPTION
**Pull request by nagaina**

### CODE REVIEW

**Comment by levibyte** [comment]
Fixed compile but some tests are crashing :/

**Comment by nagaina** [comment]
> Fixed compile but some tests are crashing :/

crash log?

**Comment by levibyte** [comment]
Stack dump
*****************************************


1       0x55a60fd983ea /home/levon/test/qt_painter/sqa/bin/../../bin/linux/painter(+0xa63ea) [0x55a60fd983ea]
2       0x7f7803d77f20 /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f7803d77f20]
3       0x7f78053ccc73 QPolygon::boundingRect() const + 3
4       0x55a60fde47b7 polygon::intersects(QRect const&) const + 47
5       0x55a60fde4611 rq::RQpolygon::intersects(QRect const&) const + 39
6       0x55a60fde16be rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 110
7       0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
8       0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
9       0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
10      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
11      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
12      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
13      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
14      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
15      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
16      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
17      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
18      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
19      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
20      0x55a60fde180a rq::RQtree<IShape>::_getObjects(std::shared_ptr<rq::CNode<IShape> >, QRect const&, int, std::vector<std::shared_ptr<rq::IRQobject>, std::allocator<std::shared_ptr<rq::IRQobject> > >&) const + 442
21      0x55a60fde09f3 rq::RQtree<IShape>::getObjects(QRect const&) const + 103
22      0x55a60fddf428 RegionQuery::getShapesUnderRect(QRect const&) const + 82
23      0x55a60fdf1898 Selection::find_and_highlightselect_shapes_from_region(std::pair<QPoint, QPoint> const&) + 186
24      0x55a60fd9fd17 dicmdSelectShapesByRegion::execute() + 419
25      0x55a60fd9dbbb DirectCommandBase::silent_execute() + 51
26      0x55a60fda01d5 incmdSelectShapesByRegion::on_commit_internal() + 95
27      0x55a60fdad214 incmdCreateObj<(ObjectType)1>::on_commit(EvType const&) + 54
28      0x55a60fdaa3e8 incmdCreateObj<(ObjectType)1>::on_first_click(EvType const&) + 128
29      0x55a60fdb312f void std::__invoke_impl<void, void (incmdCreateObj<(ObjectType)1>::*&)(EvType const&), incmdCreateObj<(ObjectType)1>*&, EvType const&>(std::__invoke_memfun_deref, void (incmdCreateObj<(ObjectType)1>::*&)(EvType const&), incmdCreateObj<(ObjectType)1>*&, EvType const&) + 125
30      0x55a60fdb29f1 std::__invoke_result<void (incmdCreateObj<(ObjectType)1>::*&)(EvType const&), incmdCreateObj<(ObjectType)1>*&, EvType const&>::type std::__invoke<void (incmdCreateObj<(ObjectType)1>::*&)(EvType const&), incmdCreateObj<(ObjectType)1>*&, EvType const&>(void (incmdCreateObj<(ObjectType)1>::*&)(EvType const&), incmdCreateObj<(ObjectType)1>*&, EvType const&) + 87
31      0x55a60fdb1a34 void std::_Bind<void (incmdCreateObj<(ObjectType)1>::*(incmdCreateObj<(ObjectType)1>*, std::_Placeholder<1>))(EvType const&)>::__call<void, EvType const&, 0ul, 1ul>(std::tuple<EvType const&>&&, std::_Index_tuple<0ul, 1ul>) + 132
32      0x55a60fdafb3a void std::_Bind<void (incmdCreateObj<(ObjectType)1>::*(incmdCreateObj<(ObjectType)1>*, std::_Placeholder<1>))(EvType const&)>::operator()<EvType const&, void>(EvType const&) + 86
33      0x55a60fdad360 std::_Function_handler<void (EvType const&), std::_Bind<void (incmdCreateObj<(ObjectType)1>::*(incmdCreateObj<(ObjectType)1>*, std::_Placeholder<1>))(EvType const&)> >::_M_invoke(std::_Any_data const&, EvType const&) + 55
34      0x55a60fda33cf std::function<void (EvType const&)>::operator()(EvType const&) const + 73
35      0x55a60fd9ee6b InteractiveCommandBase::handle_mouse_click(int, int) + 63
36      0x55a60fda0341 incmdSelectShapesByRegion::handle_mouse_click(int, int) + 113
37      0x55a60fdf9f5d command_manager::mouse_clicked(int, int) + 123
38      0x55a60fd9b081 canvas::mousePressEvent(QMouseEvent*) + 165
39      0x7f780591698f QWidget::event(QEvent*) + 2895
40      0x7f78058d782c QApplicationPrivate::notify_helper(QObject*, QEvent*) + 156
41      0x7f78058df64f QApplication::notify(QObject*, QEvent*) + 2047
42      0x7f78049559a8 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 280
43      0x55a60fd9e142 QCoreApplication::sendEvent(QObject*, QEvent*) + 56
44      0x55a60fd9e935 dicmdCanvasMouseClick::execute() + 467
45      0x55a60fd9cdbc CommandBase::execute_and_log() + 70
46      0x55a60fdc8e4a CommandInterp::execute_cmd(CommandBase*) + 102
47      0x55a60fde546a LogReader::execute_next_command() + 234
48      0x55a60fde817b /home/levon/test/qt_painter/sqa/bin/../../bin/linux/painter(+0xf617b) [0x55a60fde817b]
49      0x7f78049845b5 QMetaObject::activate(QObject*, int, int, void**) + 2149
50      0x7f7804991027 QTimer::timeout(QTimer::QPrivateSignal) + 55
51      0x7f7804991388 QTimer::timerEvent(QTimerEvent*) + 40
52      0x7f78049850db QObject::event(QEvent*) + 155
53      0x7f78058d782c QApplicationPrivate::notify_helper(QObject*, QEvent*) + 156
54      0x7f78058df0f4 QApplication::notify(QObject*, QEvent*) + 676
55      0x7f78049559a8 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 280
56      0x7f78049add8e QTimerInfoList::activateTimers() + 1038
57      0x7f78049ae551 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2e3551) [0x7f78049ae551]
58      0x7f78020ce417 g_main_context_dispatch + 743
59      0x7f78020ce650 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c650) [0x7f78020ce650]
60      0x7f78020ce6dc g_main_context_iteration + 44
61      0x7f78049ae8ef QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 95
62      0x7f78049539ea QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 314
63      0x7f780495ca84 QCoreApplication::exec() + 148
64      0x55a60fd986eb main + 192
65      0x7f7803d5ab97 __libc_start_main + 231
66      0x55a60fd97c6a _start + 42

**Comment by levibyte** [comment]
*steps to reproduce*
find design attached

dicmdDesignLoad -filename mydes.des 
dicmdSelectShapesByRegion -end (1027,469) -start (37,7)

**Comment by levibyte** [comment]
reverted all my changes

**Comment by nagaina** [comment]
> reverted all my changes

Revert all reverts 😀

**Comment by levibyte** [comment]
@nagaina 
let's dissuss the code changes beetween your version and my version.

https://github.com/mm-project/qt_painter/compare/46b52a1adf8ee71cd24d8e49ddf876c6b0610cd0...f597396

You can put comments on lines you are interested by pressing on the + and commenting.

**Pull request closed without merging**
